### ISSUE TITLE
Broken counts?

### ISSUE THREAD

**Issue by rsebbe** [daehn/CountedSet#1]
I think there's a misunderstanding on how hash work. This implementation of CountedSet is not able to maintain different counts for distinct elements that share the same hash.

I'd suggest a backing of the form: [Element : Count] instead of Set<Element> + [Hash : Count]

**Comment by daehn** [comment]
@rsebbe thanks for opening the issue, you are right that this implementation does not yet handle any hash collisions. Your suggestion sounds like a good approach to solve this issue to me.

**Comment by daehn** [comment]
The fix is included in https://github.com/daehn/Counted-Set/releases/tag/0.2.0
